// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJw8cL6BJESHhXYIM6ruOeofd-xvBot7E',
    appId: '1:183826575243:web:6b90d8313f6e968c22498e',
    messagingSenderId: '183826575243',
    projectId: 'note-mesh',
    authDomain: 'note-mesh.firebaseapp.com',
    storageBucket: 'note-mesh.appspot.com',
    measurementId: 'G-FMLEJ8V7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxEErH6wwQ5ZnvcMa_8QgEJy1A8ctV38',
    appId: '1:183826575243:android:a0c6cf292458a69f22498e',
    messagingSenderId: '183826575243',
    projectId: 'note-mesh',
    storageBucket: 'note-mesh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_C1-IWzXQtzZ33R8JKDI5BtqAqSeSP4',
    appId: '1:183826575243:ios:4255117883fd66bc22498e',
    messagingSenderId: '183826575243',
    projectId: 'note-mesh',
    storageBucket: 'note-mesh.appspot.com',
    iosBundleId: 'com.example.noteMesh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_C1-IWzXQtzZ33R8JKDI5BtqAqSeSP4',
    appId: '1:183826575243:ios:ea020ecc3bc958bd22498e',
    messagingSenderId: '183826575243',
    projectId: 'note-mesh',
    storageBucket: 'note-mesh.appspot.com',
    iosBundleId: 'com.example.noteMesh.RunnerTests',
  );
}
