import 'package:flutter/material.dart';
import 'files.dart';
import 'login.dart';
import 'sign-up.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => LoginScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/files': (context) => const FileScreen(),
      },
      initialRoute: '/',
    );
  }
}
